import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import Form from '../components/Form'

export default function Home() {
  const [openForm, setOpenForm] = useState(false);
  const [formData, setFormData] = useState({
    nome:"",
    idade:"",
    sexo:"",
    observacao:""
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <Form />
       
      </main>

      
    </div>
  )
}
